import React, { useState } from 'react';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import html2canvas from 'html2canvas';
import '../../styles/ReportGenerator.css';
import { useAuth } from '../../contexts/AuthContext';

const ReportGenerator = () => {
  const { currentUser } = useAuth();
  const [reportData, setReportData] = useState({
    title: '',
    department: '',
    academicYear: '',
    introduction: '',
    purpose: '',
    highlights: '',
    awards: '',
    programs: '',
    studentAchievements: '',
    facultyContributions: '',
    activities: '',
    infrastructure: '',
    futurePlans: '',
    conclusion: ''
  });

  const [previewMode, setPreviewMode] = useState(false);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setReportData(prevData => ({
      ...prevData,
      [name]: value
    }));
  };

  const generatePDF = () => {
    const reportElement = document.getElementById('report-preview');
    
    html2canvas(reportElement).then(canvas => {
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 10;
      
      // Add header
      pdf.setFontSize(18);
      pdf.text(reportData.title, pageWidth / 2, 20, { align: 'center' });
      
      pdf.setFontSize(12);
      pdf.text(`Department: ${reportData.department}`, margin, 30);
      pdf.text(`Academic Year: ${reportData.academicYear}`, margin, 37);
      
      // Add content
      const contentStart = 45;
      const imgWidth = pageWidth - (margin * 2);
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      
      pdf.addImage(imgData, 'PNG', margin, contentStart, imgWidth, imgHeight);
      
      // Add pagination
      const totalPages = Math.ceil(imgHeight / (pageHeight - contentStart));
      for (let i = 1; i <= totalPages; i++) {
        pdf.setFontSize(10);
        pdf.text(`Page ${i} of ${totalPages}`, pageWidth - 25, pageHeight - 10);
        if (i < totalPages) pdf.addPage();
      }
      
      // Add footer with author info
      if (currentUser) {
        pdf.setFontSize(10);
        pdf.text(`Generated by: ${currentUser.displayName || currentUser.email || 'User'}`, margin, pageHeight - 10);
        pdf.text(`Date: ${new Date().toLocaleDateString()}`, margin, pageHeight - 5);
      }
      
      pdf.save(`${reportData.department}_Annual_Report_${reportData.academicYear}.pdf`);
    });
  };

  const togglePreview = () => {
    setPreviewMode(!previewMode);
  };

  const formFields = [
    { name: 'introduction', label: 'Introduction / Overview' },
    { name: 'purpose', label: 'Purpose and Scope of the Report' },
    { name: 'highlights', label: 'Department Highlights / Achievements' },
    { name: 'awards', label: 'Awards, Rankings, Publications, Faculty Achievements' },
    { name: 'programs', label: 'Programs & Events Conducted' },
    { name: 'studentAchievements', label: 'Student Achievements' },
    { name: 'facultyContributions', label: 'Faculty Contributions' },
    { name: 'activities', label: 'Departmental Activities' },
    { name: 'infrastructure', label: 'Infrastructure / Resources Update' },
    { name: 'futurePlans', label: 'Future Plans' },
    { name: 'conclusion', label: 'Conclusion / Summary' }
  ];

  return (
    <div className="report-generator-container">
      <h2 className="text-center mb-4">Annual Report Generator</h2>
      
      {!previewMode ? (
        <div className="report-form">
          <div className="row mb-4">
            <div className="col-md-4">
              <div className="form-group">
                <label htmlFor="title">Report Title</label>
                <input
                  type="text"
                  className="form-control"
                  id="title"
                  name="title"
                  value={reportData.title}
                  onChange={handleChange}
                  placeholder="Annual Report 2024-2025"
                />
              </div>
            </div>
            <div className="col-md-4">
              <div className="form-group">
                <label htmlFor="department">Department</label>
                <input
                  type="text"
                  className="form-control"
                  id="department"
                  name="department"
                  value={reportData.department}
                  onChange={handleChange}
                  placeholder="Computer Science"
                />
              </div>
            </div>
            <div className="col-md-4">
              <div className="form-group">
                <label htmlFor="academicYear">Academic Year</label>
                <input
                  type="text"
                  className="form-control"
                  id="academicYear"
                  name="academicYear"
                  value={reportData.academicYear}
                  onChange={handleChange}
                  placeholder="2024-2025"
                />
              </div>
            </div>
          </div>

          {formFields.map((field) => (
            <div className="form-group mb-3" key={field.name}>
              <label htmlFor={field.name}>{field.label}</label>
              <textarea
                className="form-control"
                id={field.name}
                name={field.name}
                rows="4"
                value={reportData[field.name]}
                onChange={handleChange}
                placeholder={`Enter ${field.label}...`}
              />
            </div>
          ))}

          <div className="d-flex justify-content-between mt-4">
            <button className="btn btn-primary" onClick={togglePreview}>
              Preview Report
            </button>
          </div>
        </div>
      ) : (
        <div>
          <div id="report-preview" className="report-preview">
            <div className="report-header">
              <h1>{reportData.title || 'Annual Report'}</h1>
              <div className="report-meta">
                <p><strong>Department:</strong> {reportData.department}</p>
                <p><strong>Academic Year:</strong> {reportData.academicYear}</p>
                <p><strong>Generated:</strong> {new Date().toLocaleDateString()}</p>
                {currentUser && <p><strong>Author:</strong> {currentUser.displayName || currentUser.email || 'User'}</p>}
              </div>
            </div>

            {formFields.map((field) => (
              <div className="report-section" key={field.name}>
                <h3>{field.label}</h3>
                <div className="section-content">
                  {reportData[field.name] ? (
                    <p>{reportData[field.name]}</p>
                  ) : (
                    <p className="text-muted">No content added for this section.</p>
                  )}
                </div>
              </div>
            ))}
          </div>

          <div className="d-flex justify-content-between mt-4">
            <button className="btn btn-secondary" onClick={togglePreview}>
              Edit Report
            </button>
            <button className="btn btn-success" onClick={generatePDF}>
              Generate PDF
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default ReportGenerator;